language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

# command to install dependencies
install: python setup.py install

# command to run tests
script: python pyquaternion/test/test_quaternion.py

# build and deploy docs
after_script:
   - pip install mkdocs
   - mkdocs gh-deploy --clean