language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

# command to install dependencies
install: pip install .

# command to run tests
script: python setup.py test

# build and deploy docs
after_script:
   - pip install mkdocs
   - pip install mkdocs-bootswatch
   - mkdocs gh-deploy --clean