language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- nightly
install: pip install .

# command to run tests
script: python setup.py test

deploy:
  provider: pypi
  server: https://testpypi.python.org/pypitravis started

  user: kieranwynn
  password:
    secure: t1Z1Y2YU22YlzJJSlfFdYrp4QtccKuCDB0x78COCitDGtOljigjuGx7c5HkfgcGCjW0Nfofjrolc7mYssaMVZjMDQdr3JpyQa9H4/0RM8AUdXV7wtaHq54LAztVMtLqFMTCIUCputJEhzdS+31WWXZExNkUkNXasB8CEJv7Y+mvvhdTwBtulgfUgkWSiZZHDdUH+iVWlXL9KngzHQTwEVXgxUOJ1a9GTAQz3ZYHEFLLA9Ik/IaDdKmbWETMkKRLWg4yyoPMXcCf/uWbhOcmwUBLuTpLQ6vyW478yJEBkm9yYncJjRQo6nVawurlCFXuN4LILeWif1Efd9xvKI8OAQBm1cIXGlkPxNIiQtULQ197qxXMaaFAIKkqZvoxDeYWNp8hE5KVzEIoHUo3jkZjyHlLKQgscpqIfsZu2V8VbmBWrETwKN6Ts6LBOaHUKktk6qZ6kxTEYAkH/HjKi5hHbDBIVBn9MeF3s6GmOlQEf2978YtStcRTQa3siJT/XCgK5LpTYbIeo/dU+0DwMEFv/ZErKeH94Sn7RdrBqMbAmh18znxZTZv302c6vkneB9+8cgTsbQ0rvFZOuhYn69mOwLjCS1HPriy8SqXVo9tZnIUJHUUIpoWrZcHfjzKXgyvkhyw6sdlKPt1UQFs5WnuraAB3L5rFlGCIZqXA2hd/v29o=
#  on:
#    tags: true

after_script:
- git config user.name "${GITHUB_USERNAME}"
- git config user.email "${GITHUB_EMAIL}"
- git remote add gh-token "https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/pyquaternion.git";
- git fetch gh-token && git pull gh-token gh-pages:gh-pages;
- pip install mkdocs
- pip install mkdocs-bootswatch
- mkdocs gh-deploy -v --clean --remote-name gh-token;
