language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- nightly
install: pip install .
script: python setup.py test

deploy:
  provider: pypi
  user: kieranwynn
  password:
    secure: cCPH9pIl5Rr3OmJR59+kbEY8BrUV2WmOTRfCn57GOF+stwIQ2He3fYO67DxPLfB/Mb6Kxvza8IqZGLnS+gEOW+LqZmEHJerbVlej6efiJJg2w9Rq/ME6r14yZamP3JFmiWxEA+hW3gpPdQx+39FWPRMB7hTzGcPoayJCg3FeCXNMty3p3c8ZuKTZYJ0HP59WoncfKkVPExBxPxRUwUNcmD3iLLmK/LFiNcNz1pA2HvkuFUEeuuSUMROkKI13V+xM3nulr+ipUAxQM1APlZx1HoGh+Ik+2j7QpLiUXr7PQGiH9JWKVpXP3i35C0Y2CRQLRTKPT96GB7b/Di1yvgTRmsyYQpkCYXxgFxXk0jOH2P4NIAoiZHs6VH3r9UhIkP6tiqdsXU+FbzOQrQiyc5F9CicatDboNszMQU77fyyHHhqeRX/x/KmRNCCulSPz9Vl1BEpuWO58f8v14i6PLcWnBGIpaJ7KYF7ncchiOpcfftWyvcV//d/JCYowjgzQMp9iq99oShLXv2tc5qLPPS6HYEea83/WmmrRwbyeFkMWNcizh597xK6v2+9K9gxgyFjx3dYjuF8Ua6YrtTknHFrndJ2fs/+FQQy7SoudGkxhp36qgjvwGa6AXz9+X7lwRq50TEGUob0VCOGPkjUzkdyS18AvFWb2ATuHl6/Tn4aPYoo=

after_script:
- git config user.name "${GITHUB_USERNAME}"
- git config user.email "${GITHUB_EMAIL}"
- git remote add gh-token "https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/pyquaternion.git";
- git fetch gh-token && git pull gh-token gh-pages:gh-pages;
- pip install mkdocs
- pip install mkdocs-bootswatch
- mkdocs gh-deploy -v --clean --remote-name gh-token;
