site_name: pyquaternion 
pages:
- [index.md, Home]
- [quaternion_basics.md, Quaternion Basics]
- [initialisation.md, Object Initialisation]
- [features.md, Quaternion Features]
- [operations.md, Quaternion Operations]
theme: mkdocs
